<a href="https://colab.research.google.com/github/KrishnaPandya-VGEC-IT/Data-Science-/blob/main/Data_cleaning%5B1_Missing_Data%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
falsy_values = (0, False, None, '', [], {}) # all values in this set are considered as falsy or null values

In [ ]:
any(falsy_values) # any will return true if any value is valid/not null

False

In [ ]:
np.nan #nan stands for not a number it usually shows null value 

nan

In [ ]:
3 + np.nan # 3 + not a number is not a number

nan

In [ ]:
a = np.array([1,2,3,np.nan,None,4], dtype = float) # np.nan is like virus. If you have it in an array and you perform some operations then results will be unexpected.

In [ ]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [ ]:
a.mean()

nan

In [ ]:
a.sum()

nan

In [ ]:
np.inf # which also behaves as a virus

inf

In [ ]:
3 + np.inf 

inf

In [ ]:
np.inf/3

inf

In [ ]:
np.inf / np.inf

nan

In [ ]:
b = np.array([1,2,3,np.inf,np.nan,None, 4],dtype = float)

In [ ]:
b

array([ 1.,  2.,  3., inf, nan, nan,  4.])

In [ ]:
b.sum() # obviously nan

nan

**Checking for nan or inf**

In [ ]:
np.isnan(np.nan) #nan is nan

True

In [ ]:
np.isinf(np.inf)

True

In [ ]:
np.isinf(np.nan)

False

In [ ]:
np.isnan(np.inf)

False

In [ ]:
np.isnan(np.array([0,1,2,np.nan,np.inf]))

array([False, False, False,  True, False])

In [ ]:
np.isinf(np.array([0,1,2,np.nan,np.inf]))

array([False, False, False, False,  True])

**Filtering them out**

In [ ]:
a = np.array([1,2,3,np.nan,np.nan,4])

In [ ]:
a[~np.isnan(a)] # return those values which are not null

array([1., 2., 3., 4.])

In [ ]:
a[np.isfinite(a)] # similar to above

array([1., 2., 3., 4.])

In [ ]:
a[np.isfinite(a)].sum()

10.0

In [ ]:
a[np.isfinite(a)].mean()

2.5